### ISSUE TITLE
Error connecting to test.mosquitto.org

### ISSUE THREAD

**Issue by rosshigh** [ako/MqttClient#10]
I'm attempting to use the Mendix Appstore version in Mendix app using version 7.21.0 of the modeler.  My config is:
Broker host: test.mosquitto.org
Broker port: 1883
Broker org: empty
Timeout 120
Username: empty
Password: empty
Topic: One Climate Device/Climate w Light
Microflow: a microflow in the project
the rest of the parameters are empty.

When I try to connect I get this error in the console:

```
--------

org.eclipse.paho.client.mqttv3.MqttException: Connection lost
	at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:164)
	at java.lang.Thread.run(Thread.java:748)

Caused by: java.io.EOFException: null
	at java.io.DataInputStream.readByte(DataInputStream.java:267)
	at org.eclipse.paho.client.mqttv3.internal.wire.MqttInputStream.readMqttWireMessage(MqttInputStream.java:92)
	at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:116)
	at java.lang.Thread.run(Thread.java:748)
```

It seems a simple enough thing to configure but I must be missing something.  Any help would be greatly appreciated.

Ross

**Comment by rosshigh** [comment]
The problem was that I had set the Qos field to empty. Once I put a value in that field, it worked.

Ross
